//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalGuard_Inspection_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int task_detail_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string category { get; set; }
        public string assign_to { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<System.DateTime> reminder_datetime { get; set; }
        public string location { get; set; }
        public string notes { get; set; }
        public string image { get; set; }
        public string files { get; set; }
        public string link { get; set; }
        public string comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    
        public virtual M_Task M_Task { get; set; }
    }
}
